"use client";

import { FormEvent, useEffect, useState } from "react";
import { DailyReading, ModelStatus, Scene, UserProfile, WardrobeItem } from "@/lib/types";
import { storage } from "@/lib/storage";
import { demoReading } from "@/lib/demo-reading";
import { findWardrobeMatches } from "@/lib/outfit-matcher";
import { getDailyCacheKey, localDateKey } from "@/lib/cache-key";

const scenes: Scene[] = ["通勤", "休闲", "约会"];
const categories = ["上装", "下装", "连衣裙", "外套", "鞋履", "配饰"] as const;
const demoWardrobe: WardrobeItem[] = [
  { id: "white-shirt", name: "玉白棉质衬衫", category: "上装", primaryColor: "玉白", scenes: ["通勤", "约会"], seasons: ["春", "秋"], tags: ["极简"], enabled: true },
  { id: "green-pants", name: "苔藓绿阔腿裤", category: "下装", primaryColor: "苔藓绿", scenes: ["通勤", "休闲"], seasons: ["春", "夏"], tags: ["舒适"], enabled: true },
  { id: "blue-jacket", name: "雾蓝短外套", category: "外套", primaryColor: "雾蓝", scenes: ["约会", "通勤"], seasons: ["春", "秋"], tags: ["轻盈"], enabled: true },
];

function Nav({ active, setActive }: { active: string; setActive: (value: string) => void }) {
  return <nav className="nav"><button className="brand" onClick={() => setActive("today")}>五行·日常</button><div className="nav-links">{[["today", "今日灵感"], ["wardrobe", "我的衣橱"], ["profile", "个人档案"], ["settings", "模型设置"]].map(([id, label]) => <button key={id} className={active === id ? "active" : ""} onClick={() => setActive(id)}>{label}</button>)}</div></nav>;
}

export default function Home() {
  const [active, setActive] = useState("today");
  const [profile, setProfile] = useState<UserProfile | null>(null);
  const [wardrobe, setWardrobe] = useState<WardrobeItem[]>(demoWardrobe);
  const [reading, setReading] = useState<DailyReading>(demoReading());
  const [status, setStatus] = useState<ModelStatus>({ configured: false, provider: "DeepSeek", model: "deepseek-chat", baseURL: "https://api.deepseek.com/v1", promptVersion: "style-v2" });
  const [loading, setLoading] = useState(false); const [error, setError] = useState(""); const [cacheHit, setCacheHit] = useState(false); const [loaded, setLoaded] = useState(false);

  useEffect(() => { const savedProfile = storage.profile(); const savedWardrobe = storage.wardrobe(); const nextWardrobe = savedWardrobe.length ? savedWardrobe : demoWardrobe; setProfile(savedProfile); setWardrobe(nextWardrobe); const cached = storage.dailyReading(getDailyCacheKey(savedProfile, nextWardrobe)); if (cached) { setReading(cached); setCacheHit(true); } else { setReading(demoReading()); setCacheHit(false); } fetch("/api/model-status").then(r => r.json()).then(setStatus).catch(() => undefined).finally(() => setLoaded(true)); }, []);
  useEffect(() => { if (!loaded) return; const cached = storage.dailyReading(getDailyCacheKey(profile, wardrobe)); if (cached) { setReading(cached); setCacheHit(true); } else { setReading(demoReading()); setCacheHit(false); } }, [profile, wardrobe, loaded]);
  const persistWardrobe = (items: WardrobeItem[]) => { setWardrobe(items); storage.setWardrobe(items); const cached = storage.dailyReading(getDailyCacheKey(profile, items)); if (cached) { setReading(cached); setCacheHit(true); } else { setReading(demoReading()); setCacheHit(false); } };
  const generate = async () => { const cacheKey = getDailyCacheKey(profile, wardrobe); const cached = storage.dailyReading(cacheKey); if (cached) { setReading(cached); setCacheHit(true); setError(""); return; } setLoading(true); setError(""); try { const response = await fetch("/api/daily-reading", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ profile, wardrobe, date: localDateKey() }) }); if (!response.ok) throw new Error(); const next = await response.json() as DailyReading; storage.setDailyReading(cacheKey, next); setReading(next); setCacheHit(false); setActive("today"); } catch { setError("生成暂时不可用，请确认服务端 API 配置后重试。"); } finally { setLoading(false); } };
  if (!loaded) return <main className="loading">正在整理今日的生活灵感…</main>;
  return <main><Nav active={active} setActive={setActive} />{active === "today" && <Today reading={reading} wardrobe={wardrobe} onGenerate={generate} loading={loading} error={error} cacheHit={cacheHit} onNavigate={setActive} />}{active === "wardrobe" && <Wardrobe items={wardrobe} setItems={persistWardrobe} />}{active === "profile" && <Profile profile={profile} setProfile={setProfile} />}{active === "settings" && <Settings status={status} profile={profile} wardrobe={wardrobe} onClear={() => { storage.clearAll(); setProfile(null); setWardrobe([]); setReading(demoReading()); }} />}</main>;
}

function Today({ reading, wardrobe, onGenerate, loading, error, cacheHit, onNavigate }: { reading: DailyReading; wardrobe: WardrobeItem[]; onGenerate: () => void; loading: boolean; error: string; cacheHit: boolean; onNavigate: (v: string) => void }) {
  const style = reading.dailyStyle;
  return <div className="page"><section className="hero"><p className="eyebrow">DAILY STYLE · {reading.date}</p><div className="hero-grid"><div><span className="orb">日</span><p className="theme-label">{style.theme}</p><h1>{style.headline}</h1><p className="hero-copy">{style.energy}</p><button className="primary" disabled={loading} onClick={onGenerate}>{loading ? "正在生成…" : cacheHit ? "查看今日缓存" : "生成今日内容"} <span>↗</span></button>{cacheHit && <p className="cache-note">已使用今天此档案与衣橱的缓存结果</p>}{error && <p className="hero-error">{error}</p>}</div><div className="quote-card"><span>今日生活主题</span><strong>色</strong><p>色彩与穿搭的轻松提示，不等同于你的命盘五行结论。</p>{reading.source === "demo" && <em>演示内容 · 未连接模型</em>}</div></div></section><section className="profile-reading"><div><p className="eyebrow">PROFILE REFERENCE</p><h2>{reading.profileReading.title}</h2><p>{reading.profileReading.summary}</p></div><div className="tendency-list">{reading.profileReading.tendencies.map(item => <div key={item.element}><b>{item.element}</b><span>{item.level}</span><small>{item.note}</small></div>)}</div><p className="reading-note">{reading.profileReading.disclaimer}</p></section><section className="color-section"><div className="section-heading"><p className="eyebrow">COLOR DIRECTION</p><h2>今日色彩方向</h2></div><div className="palette-grid"><Palette title="幸运色" colors={style.luckyColors} /><Palette title="辅助色" colors={style.supportingColors} /><Palette title="谨慎色" colors={style.mindfulColors} /></div></section><section className="outfit-section"><div className="section-heading"><p className="eyebrow">OUTFIT NOTES</p><h2>把灵感穿进日常</h2><p>从你的衣橱里挑选，或按配色公式自由替换。</p></div><div className="outfit-grid">{style.outfits.map((outfit, index) => <article className="outfit-card" key={outfit.scene}><div className="number">0{index + 1}</div><p className="eyebrow">{outfit.scene}</p><h3>{outfit.title}</h3><p className="formula">{outfit.formula}</p><p>{outfit.reason}</p><div className="match-list">{findWardrobeMatches(wardrobe, outfit, reading).map(item => <span key={item.id}><i style={{ background: colorValue(item.primaryColor) }} />{item.name}</span>)}{!findWardrobeMatches(wardrobe, outfit, reading).length && <button onClick={() => onNavigate("wardrobe")}>去添加衣物 →</button>}</div><p className="alternative">替代：{outfit.alternative}</p></article>)}</div></section><p className="disclaimer">传统文化娱乐与生活方式灵感，仅供参考；请勿将内容作为任何重要决定的依据。</p></div>;
}
function Palette({ title, colors }: { title: string; colors: DailyReading["dailyStyle"]["luckyColors"] }) { return <article className="palette"><h3>{title}</h3>{colors.map(color => <div className="color-row" key={color.name}><i style={{ backgroundColor: color.hex }} /><div><strong>{color.name}</strong><span>{color.note}</span></div></div>)}</article>; }
function colorValue(color: string) { return color.includes("绿") ? "#667A51" : color.includes("蓝") ? "#91A8B9" : color.includes("褐") ? "#8A6C4A" : "#EAE5D7"; }

function Wardrobe({ items, setItems }: { items: WardrobeItem[]; setItems: (items: WardrobeItem[]) => void }) { const [name, setName] = useState(""); const [color, setColor] = useState("苔藓绿"); const [category, setCategory] = useState<typeof categories[number]>("上装"); const [scene, setScene] = useState<Scene>("通勤"); const add = (e: FormEvent) => { e.preventDefault(); if (!name.trim()) return; setItems([{ id: crypto.randomUUID(), name, primaryColor: color, category, scenes: [scene], seasons: ["春", "秋"], tags: [], enabled: true }, ...items]); setName(""); }; return <div className="page narrow"><header className="page-header"><p className="eyebrow">PERSONAL WARDROBE</p><h1>我的衣橱</h1><p>记录可穿单品，让每日灵感真正落到你的衣架上。</p></header><form className="item-form" onSubmit={add}><input value={name} onChange={e => setName(e.target.value)} placeholder="衣物名称，例如：玉白衬衫" /><input value={color} onChange={e => setColor(e.target.value)} placeholder="主色" /><select value={category} onChange={e => setCategory(e.target.value as typeof category)}>{categories.map(item => <option key={item}>{item}</option>)}</select><select value={scene} onChange={e => setScene(e.target.value as Scene)}>{scenes.map(item => <option key={item}>{item}</option>)}</select><button className="primary">添加单品</button></form><div className="wardrobe-grid">{items.map(item => <article className="wardrobe-card" key={item.id}><div className="cloth-shape"><i style={{ background: colorValue(item.primaryColor) }} /></div><div><p className="eyebrow">{item.category} · {item.scenes.join(" / ")}</p><h3>{item.name}</h3><span>{item.primaryColor}</span></div><button className="delete" onClick={() => setItems(items.filter(candidate => candidate.id !== item.id))}>移除</button></article>)}</div></div>; }

function Profile({ profile, setProfile }: { profile: UserProfile | null; setProfile: (profile: UserProfile) => void }) { const [form, setForm] = useState<UserProfile>(profile ?? { birthDate: "", lunarBirthDate: "", birthTime: "", birthPlace: "", gender: "不透露", bazi: "", reflectionAnswers: ["", ""], scenes, styles: ["自然简约"], favoriteColors: ["苔藓绿"], avoidColors: [] }); const update = (key: keyof UserProfile, value: string | string[]) => setForm({ ...form, [key]: value }); const save = (e: FormEvent) => { e.preventDefault(); if (!form.birthDate && !form.lunarBirthDate && !form.bazi) return; setProfile(form); storage.setProfile(form); }; return <div className="page narrow"><header className="page-header"><p className="eyebrow">PERSONAL REFERENCE</p><h1>个人档案</h1><p>可输入出生资料或自行提供的八字，用于生成娱乐性质的基础倾向；系统不会自行排盘。</p></header><form className="profile-form" onSubmit={save}><div className="form-two"><label>公历出生日期<input type="date" value={form.birthDate} onChange={e => update("birthDate", e.target.value)} /></label><label>农历出生日期<input value={form.lunarBirthDate} onChange={e => update("lunarBirthDate", e.target.value)} placeholder="例如：1998年八月初三" /></label><label>性别<select value={form.gender} onChange={e => update("gender", e.target.value)}><option>不透露</option><option>女</option><option>男</option></select></label><label>出生时间（可选）<input type="time" value={form.birthTime} onChange={e => update("birthTime", e.target.value)} /></label></div><label>出生地点（可选）<input value={form.birthPlace} onChange={e => update("birthPlace", e.target.value)} placeholder="例如：杭州" /></label><label>自行提供的八字（可选）<input value={form.bazi} onChange={e => update("bazi", e.target.value)} placeholder="例如：甲子 乙丑 丙寅 丁卯" /></label><div className="reflection"><span>自我回顾（可跳过）</span><small>帮助你把内容理解为个人反思，而不是对既往事件的断言。</small>{(form.reflectionAnswers ?? ["", ""]).map((value, i) => <input key={i} value={value} onChange={e => update("reflectionAnswers", (form.reflectionAnswers ?? ["", ""]).map((item, index) => index === i ? e.target.value : item))} placeholder={i === 0 ? "例如：近年是否经历过学习或工作节奏变化？" : "例如：高压时你通常怎样恢复状态？"} />)}</div><button className="primary">保存档案</button></form></div>; }

function Settings({ status, profile, wardrobe, onClear }: { status: ModelStatus; profile: UserProfile | null; wardrobe: WardrobeItem[]; onClear: () => void }) { return <div className="page narrow"><header className="settings-hero"><p className="eyebrow">MODEL CONSOLE</p><div><h1>模型设置</h1><span className={`status ${status.configured ? "ready" : "demo"}`}>{status.configured ? "已连接 API" : "演示模式"}</span></div><p>在这里确认服务端模型状态，并管理当前浏览器的本地资料。生成入口位于“今日灵感”卡片。</p></header><section className="console-card connection"><div className="card-kicker">01 · CONNECTION</div><div className="connection-grid"><div><h3>{status.configured ? "DeepSeek 已就绪" : "尚未配置服务端 Key"}</h3><p>{status.configured ? "今日灵感卡片将使用 DeepSeek 生成基础五行倾向与今日生活主题。" : "当前可使用完整演示流程。要调用模型，请在项目根目录创建 .env.local。"}</p></div><dl><div><dt>供应商</dt><dd>{status.provider}</dd></div><div><dt>模型</dt><dd>{status.model}</dd></div><div><dt>Base URL</dt><dd>{status.baseURL}</dd></div><div><dt>提示词</dt><dd>{status.promptVersion}</dd></div><div><dt>输出</dt><dd>结构化 JSON</dd></div></dl></div></section>{!status.configured && <section className="console-card setup"><div className="card-kicker">02 · SETUP</div><h3>连接步骤</h3><ol><li>在项目根目录创建 <code>.env.local</code>。</li><li>填写 <code>DEEPSEEK_API_KEY</code>。</li><li>按需填写 <code>DEEPSEEK_MODEL</code> 和 <code>DEEPSEEK_BASE_URL</code>。</li><li>重启开发服务后回到“今日灵感”生成内容。</li></ol><p>密钥只由服务端读取，不会显示、保存或发送至浏览器。</p></section>}<details className="console-card boundaries"><summary><span>03 · 生成边界</span><b>+</b></summary><div><p><strong>基础五行倾向</strong> 是基于你自填资料生成的传统文化娱乐性解读，不是自动排盘或专业命理结论。</p><p><strong>今日生活主题</strong> 是独立的色彩与穿搭灵感，不代表“今日五行”或对个人状态的确定判断。</p></div></details><section className="console-card data-control"><div className="card-kicker">04 · LOCAL DATA</div><h3>浏览器本地数据</h3><div className="data-stats"><span>档案 <b>{profile ? 1 : 0}</b></span><span>衣橱 <b>{wardrobe.length}</b></span><span>灵感记录 <b>1</b></span></div><p>所有资料默认仅保存于当前浏览器。清除后不可恢复。</p><button className="outline" onClick={() => { if (window.confirm("确定删除此浏览器中的所有本地数据吗？")) onClear(); }}>清除全部本地数据</button></section></div>; }
